%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\martin.murtagh\OneDrive - Wrights Group Ltd\Testing\Setups\dbc files\AT330_DoubleDeckEV\CAN_System_WB.dbc
%
% Auto-generated by MATLAB on 26-Nov-2021 10:56:55

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = [" ", ":", "@", "|"];

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "unit"];
opts.VariableTypes = ["string", "categorical", "string", "string", "double", "double", "double", "double", "double", "double", "double", "string", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName3", "VarName4", "VarName12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName12", "unit"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName8", "VarName9", "VarName10", "VarName11"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName8", "VarName9", "VarName10", "VarName11"], "ThousandsSeparator", ",");

% Import the data
CANSystemWB = readtable("C:\Users\martin.murtagh\OneDrive - Wrights Group Ltd\Testing\Setups\dbc files\AT330_DoubleDeckEV\CAN_System_WB.dbc", opts);


%% Clear temporary variables
clear opts