%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\martin.murtagh\OneDrive - Wrights Group Ltd\Testing\Setups\dbc files\AT330_DoubleDeckEV\CAN_System_WB.dbc
%
% Auto-generated by MATLAB on 26-Nov-2021 11:06:22

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = [" ", ":", "@", "|"];

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "unit"];
opts.VariableTypes = ["char", "char", "char", "char", "double", "double", "double", "double", "double", "double", "double", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName12", "unit"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName12", "unit"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName8", "VarName9", "VarName10", "VarName11"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName8", "VarName9", "VarName10", "VarName11"], "ThousandsSeparator", ",");

% Import the data
CANSystemWB = readtable("C:\Users\martin.murtagh\OneDrive - Wrights Group Ltd\Testing\Setups\dbc files\AT330_DoubleDeckEV\CAN_System_WB.dbc", opts);

%% Convert to output type
CANSystemWB = table2cell(CANSystemWB);
numIdx = cellfun(@(x) ~isnan(str2double(x)), CANSystemWB);
CANSystemWB(numIdx) = cellfun(@(x) {str2double(x)}, CANSystemWB(numIdx));

%% Clear temporary variables
clear opts